name: Smonkey CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Create Application.yml
      - uses: actions/checkout@v3
        run: |
            touch ./src/main/resources/application.properties
            echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.properties
            cat ./src/main/resources/application.properties

      - name: Build with Gradle
        run: |
            chmod +x ./gradlew
            ./gradlew clean build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/build/libs/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'smonkey'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_07AC96F3E7AE4CF5B8427AFDF6CD41E8 }}
          package: '*.jar'
